### ISSUE TITLE
more options 

### ISSUE THREAD

**Issue by mkeyno** [ajfoul/thlaser-inkscape-plugin#1]
hi @ajfoul  and thanks for sharing the code , I've tried your code in actual cnc laser but I think like the TurnkeyTyranny code , need more options and modification , for example when using the cutting machine such as plasma or laser , need piercing and wait couple of time to tools (cutting device) warm up and be ready , unfortunately I'm not python expert to help you but if you add such option kindly let me know

BR

**Comment by ajfoul** [comment]
Hi @mkeyno, 

I'm not sure I understand why a laser or plasma cutter would need to warm up, they are both instant on machines as far as I know.

I am actually not using the Inkscape plugin for much anymore, just some occasional raster stuff and then only when I can get Inkscape to run on my Mac. I mostly use Autodesk Fusion360 now. Helped them implement a post processor for Smoothieware (and also Marlin) which allows direct output of gcode. The Smoothie Post is now built-in to F360 and the Marlin version is available in [my repo](https://github.com/ajfoul/F360-Posts-Smoothie) 

You might also want to join us over at the [Opensource Laser Google group](https://groups.google.com/forum/?#!forum/opensource-laser), lots of people there who are quite knowledgeable and may be able to address your needs.

regards,
aj
